# Introdução ao R

No R, tudo é um objeto. Objetos podem ser de diferentes tipos, como vetores, matrizes, listas, data frames, funções, etc. Atribuímos valores a objetos usando o operador `<-`. Por exemplo:

In [1]:
a <- 8
10 -> b
a
b

[1] 8

[1] 10

> Note que é possível usar tanto `<-` quanto `->` para atribuição, mas a convenção é sempre usar `<-`.

## Variáveis

O R possui uma relação muito similar com o python quando se trata de variáveis. Por exemplo, você pode criar uma variável `a` e atribuir um valor a ela, e depois criar outra variável `b` e atribuir outro valor. Você pode acessar o valor de uma variável simplesmente digitando seu nome.

R não é fortemente tipado, o que significa que você pode mudar o tipo de um objeto ao longo do tempo. Por exemplo:

In [2]:
a <- 8
a
a <- "Oito"
a

[1] 8

[1] "Oito"

Porém, é possível utilizar funções como `is.numeric()` para verificar o tipo de um objeto.

Além disso, variáveis do tipo bool são um caso especial, pois podem assumir apenas dois valores: `TRUE` ou `FALSE`, porém são tratadas como 1 ou 0 no R. Fazendo com que coisas assim possam acontecer:

In [3]:
booleano <- TRUE
x <- 1

# Comparando booleano com x
booleano == x  # TRUE, pois TRUE é tratado como 1

[1] TRUE

Por outro lado, se você fizer uma operação matemática com um booleano, ele será convertido para 1 ou 0.  Por exemplo:

In [4]:
booleano + x  # 1
x + booleano  # 2

booleano * x  # 1

[1] 2

[1] 2

[1] 1

Mas, se utilizarmos um operador de negação, o resultado das contas tendem a possuir o tipo da primeira variável. Por exemplo:

In [5]:
!booleano + x # FALSE, pois a primeira variável é booleana
x + !booleano # 1, pois a primeira variável é numerica

[1] FALSE

[1] 1

### Nomes de variáveis

É válido ressaltar que em R o `.` (ponto) é um caractere válido para nomes de objetos, mas não é recomendado começar nomes de objetos com números ou usar caracteres especiais. Para acessar atributos de um objeto, você pode usar o operador `$`. Por exemplo:

In [6]:
cliente.nome <- "Lucas"
cliente.nome

[1] "Lucas"

In [7]:
# Criando um objeto cliente com atributos
cliente <- list(nome = "Lucas", idade = 30, cidade = "São Paulo")

# Acessando atributos do objeto cliente
cliente$nome
cliente$idade
cliente$cidade

[1] "Lucas"

[1] 30

[1] "São Paulo"

R possui algumas peculiaridades em relação a nomes de variáveis. Por exemplo, nomes de variáveis podem conter letras, números e o caractere `_`, mas não podem começar com um número. Além disso, R é case-sensitive, ou seja, `variavel` e `Variavel` são consideradas variáveis diferentes.

## Funções

Em R, funções são objetos de primeira classe, o que significa que você pode atribuí-las a variáveis, passá-las como argumentos para outras funções e retorná-las de funções. Por exemplo:

In [8]:
soma <- function(x, y) {
  return(x + y)
}
soma(2, 3)

[1] 5

Além disso, R possui muitas funções embutidas que você pode usar diretamente. Exemplo das principais funções embutidas:

In [9]:
# mean() -> Calcula a média de um vetor
mean(c(1, 2, 3, 4, 5))

[1] 3

In [10]:
# rm(lista) -> remove uma variável da memória
rm(a, b)

In [11]:
# rep(c(), x) -> concatena um vetor (ou não) com ele mesmo x vezes
rep(c(1, 2, 3), 3)

[1] 1 2 3 1 2 3 1 2 3

In [12]:
# sum(c()) -> soma uma lista inteira
sum(c(1, 2, 3, 4, 5))

[1] 15

In [13]:
# sqrt(x) -> faz raíz quadrada de um número
# pode ser usado um vetor de parâmetro para aplicar a cada item do vetor
sqrt(4)
sqrt(c(1, 4, 9, 16))

[1] 2

[1] 1 2 3 4

In [14]:
# ls() -> Lista as variáveis carregadas na memória no momento
ls()

[1] "booleano"     "cliente"      "cliente.nome" "soma"         "x"

In [15]:
# save(var, file = "nome_do_arquivo.RData") -> Salva um objeto em um arquivo .RData
save(cliente, file = "cliente.RData")

In [16]:
# load("nome_do_arquivo.RData") -> Carrega um objeto salvo em um arquivo .RData
load("cliente.RData")

## Vetores

Em R, tudo é vetor, porém, podemos criar nossos próprios vetores utilizando a função `c()`.

In [17]:
v <- c(1,9,0,3,4,8,6,0,9,8)
v

 [1] 1 9 0 3 4 8 6 0 9 8

O acesso ao vetor é feito como em outras linguagens através do `vetor[index]`, porém é importante ressaltar, que R não possui indexação como em outras linguagens, o index inicial é o `1` e não o `0`.

In [18]:
v[1]
v[2]
v[3]

[1] 1

[1] 9

[1] 0

Também é possível selecionar uma lista de indíces para serem exibidos. Neste caso, o resultado será um novo vetor.

In [19]:
v[c(1, 2, 3)]

[1] 1 9 0

Além disso, é possível selecionar valores negativos no índice, o que irá fazer com que o vetor apresente todos os índices, menos o selecionado. Além de possuir uma variação com um vetor de indíces.

In [20]:
v[-1]
v[-c(1,2,3)]

[1] 9 0 3 4 8 6 0 9 8

[1] 3 4 8 6 0 9 8

Além disso, é possível fazer operações com vetores, por exemplo:

In [21]:
v1 <- c(1, 2, 3, 4, 5)
v2 <- c(4, 5, 6, 7, 8)

# Opera a cada valor do vetor
v1 + v2
v1 - v2
v1 + 1

# Concatena os vetores
c(v1, v2)

[1]  5  7  9 11 13

[1] -3 -3 -3 -3 -3

[1] 2 3 4 5 6

 [1] 1 2 3 4 5 4 5 6 7 8

Para vetores de tamanhos diferentes, há uma pequena diferença. Quando o vetor menor chega no último valor, ele volta do início operando novamente, gerando sempre, como resultado, um vetor do tamanho do maior. Caso o objeto maior seja múltiplo do menor, operará normalmente, caso contrário, irá operar, porém gerar um warning. Por exemplo:

In [22]:
v3 <- c(20:29)
v4 <- c(1:4)

# Soma de vetores de mesmo tamanho
v1 + v2

# Soma de vetores de tamanho múltiplo
v1 + v3

# Soma de vetores de tamanhos diferentes
v1 + v4

[1]  5  7  9 11 13

 [1] 21 23 25 27 29 26 28 30 32 34

Warning message in v1 + v4:
“comprimento do objeto maior não é múltiplo do comprimento do objeto menor”

[1] 2 4 6 8 6

Existem formas simples de fazer uma filtragem em vetores, principalmente numéricos. Caso haja um vetor booleano, o resultado será o vetor com apenas com os valores `TRUE`.

In [23]:
v5 <- c(1:10)
v5

# Criando o filtro
filtro <- v5 %% 2 == 0
filtro

v5[filtro]

 [1]  1  2  3  4  5  6  7  8  9 10

 [1] FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE

[1]  2  4  6  8 10

É possível adicionar valores em posições específicas do vetor, por exemplo `v[5]`. Porém, caso a posição que tente adicionar seja uma posição maior que a última posição, o vetor é preenchido com `<NA>` (o `null` de outras linguagens) até a posição desejada.

In [24]:
v
v[15] <- 10
v

 [1] 1 9 0 3 4 8 6 0 9 8

 [1]  1  9  0  3  4  8  6  0  9  8 NA NA NA NA 10

Quando se há tipos de diferentes de dados em vetores, algumas coisas podem acontecer.

Primeiro, operações podem ser feitas entre vetores de tipos numéricos e tipos derivados de numéricos, como o booleano.

Segundo, quando há a concatenação de vetores, o tipo mais primitivo tende a ser usado para o resultado final, seguindo a ordem de `character` > `numeric` > `boolean`. Exemplos:

In [25]:
v1 <- c(1,2,3)
v2 <- c(FALSE,TRUE,FALSE)
v3 <- c('A','B','C')

# numeric + boolean
v1 + v2

# numeric + character = error
# v1 + v3

# concat: numeric + boolean
c(v1, v2)

# concat: numeric + character
c(v1, v3)

# concat: boolean + character
c(v2, v3)

[1] 1 3 3

[1] 1 2 3 0 1 0

[1] "1" "2" "3" "A" "B" "C"

[1] "FALSE" "TRUE"  "FALSE" "A"     "B"     "C"

### Matriz

Matrizes nada mais são do que vetores com mais de uma dimensão. Em R, é possível fazer isso de forma simples utilizando a função `matrix()`. Para utilizá-la, é preciso passar alguns parâmetros: um vetor e `ncol` = quantidade de colunas que terá ou `nrow` = quantidade de linhas que terá. Normalmente, caso você utilize `ncol`, a tabela será construída por colunas, mas é possível fazer que ela seja construída por linhas usando o parâmetro `byrow=TRUE`. O caso contrário (`nrow` e `byrow=FALSE`) também pode ser feito.

Além disso, o número de colunas (ou de linhas) deve ser um divisor do tamanho do vetor, caso contrário, ele gerará um warning avisando, mas fará o mesmo que fez com as operações entre vetores, começará a repetir o vetor para preencher as lacunas.

In [26]:
v <- 1:12

vcol <- matrix(v, ncol = 3)
vrow <- matrix(v, nrow = 3)

vcol_byrow <- matrix(v, ncol = 3, byrow = TRUE)
vrow_bycol <- matrix(v, nrow = 3, byrow = FALSE)

v_wrongCol <- matrix(v, ncol = 5, byrow = TRUE)

vcol
vrow
vcol_byrow
vrow_bycol
v_wrongCol

Warning message in matrix(v, ncol = 5, byrow = TRUE):
“data length [12] is not a sub-multiple or multiple of the number of columns [5]”

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

     [,1] [,2] [,3] [,4]
[1,] 1    4    7    10
[2,] 2    5    8    11
[3,] 3    6    9    12

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12

     [,1] [,2] [,3] [,4]
[1,] 1    4    7    10
[2,] 2    5    8    11
[3,] 3    6    9    12

     [,1] [,2] [,3] [,4] [,5]
[1,]  1    2   3    4     5
[2,]  6    7   8    9    10
[3,] 11   12   1    2     3

## DataFrame

DataFrames são conjuntos de dados, onde teremos uma tabela com atributos e seus valores. Para montá-los são necessários vetores de tamanhos iguais (se forem diferentes serão preenchidos como `<NA>`). Onde o próprio nome da variável será usado como cabeçalho. Exemplo:

In [27]:
nome <- c("Abel","Bianca","Caio","Dênis","Ema", "Fabio", "Gus", "Helena")
nota <- c(   6.5,     9.3,   2.2,    6.9,  7.0,     8.4,   7.1,      7.9)
freq <- c(  0.68,    0.81,  0.57,   0.71, 0.83,    0.90,  0.85,     0.78)
sexo <- c(   'M',     'F',   'M',    'M',  'F',     'M',   'X',      'F')

alunos <- data.frame(nome,nota,freq,sexo)
alunos

  nome   nota freq sexo
1 Abel   6.5  0.68 M
2 Bianca 9.3  0.81 F
3 Caio   2.2  0.57 M
4 Dênis  6.9  0.71 M
5 Ema    7.0  0.83 F
6 Fabio  8.4  0.90 M
7 Gus    7.1  0.85 X
8 Helena 7.9  0.78 F

Assim como as matrizes, nos DataFrames podemos utilizar coordenadas para pegar dados específicos. Por exemplo:

In [28]:
# Pegando valores específicos:
alunos[2,3]

# Pegando intervalos
alunos[2:5, 1]

# Pegando listas
alunos[c(2, 5, 7), c(1, 2, 3)]

[1] 0.81

[1] "Bianca" "Caio"   "Dênis"  "Ema"

  nome   nota freq
2 Bianca 9.3  0.81
5 Ema    7.0  0.83
7 Gus    7.1  0.85

Para acessar os dados, podemos utilizar também os `$`, pegando assim a coluna inteira. Permitindo que possamos fazer diversas coisas, inclusive operações. Por exemplo:

In [29]:
# Nome dos alunos com nota maior que 80%:
alunos[alunos$freq > 0.8, 1]

# Média dos alunos com frequência maior que 75%:
mean(alunos[alunos$freq > 0.75, 2])

[1] "Bianca" "Ema"    "Fabio"  "Gus"

[1] 7.94

## 4. Manipulação Avançada de DataFrames e Fatores
DataFrames são as estruturas centrais em Ciência de Dados com R. Além das consultas básicas por índice, podemos criar colunas calculadas, filtrar observações usando funções dedicadas e trabalhar com variáveis categóricas (`factors`).

In [ ]:
# Criando novas colunas condicionais no DataFrame alunos
alunos$aprovado <- alunos$nota >= 6.0 & alunos$freq >= 0.75
alunos$desempenho <- ifelse(alunos$nota >= 8.5, "Excelente",
                     ifelse(alunos$nota >= 6.0, "Bom", "Insuficiente"))

# Uso de subset para filtragem limpa e legível
aprovados_destaque <- subset(alunos, nota >= 7.0 & freq >= 0.80)
print("Alunos aprovados com destaque:")
print(aprovados_destaque)

# Variáveis categóricas (factors) e tabulação de frequências
alunos$sexo_fator <- factor(alunos$sexo, levels = c("M", "F", "X"), labels = c("Masculino", "Feminino", "Outro"))
print("\nDistribuição por sexo:")
print(table(alunos$sexo_fator))

# Inspeção estrutural completa do DataFrame
print("\nResumo estatístico do DataFrame:")
summary(alunos)
print("\nEstrutura interna das colunas (str):")
str(alunos)

## 5. Entrada e Saída de Dados (I/O) e Gerenciamento de Memória
Na prática de Ciência de Dados, os dados raramente vêm prontos em vetores manuais. Carregamos arquivos em formatos como CSV, TXT, arquivos comprimidos (`.zip`) ou formatos nativos do R (`.RData`). Também é crucial gerenciar a memória do ambiente de trabalho.

In [ ]:
# 1. Leitura de dados tabulares (CSV) com parâmetros essenciais
# - sep: caractere delimitador (vírgula, ponto-e-vírgula ou tabulação)
# - dec: separador de casa decimal (ponto '.' ou vírgula ',')
# - na.strings: caracteres que devem ser interpretados como ausentes (NA)
# - stringsAsFactors: define se colunas de texto viram fatores automaticamente (recomendado FALSE)

# Exemplo de leitura de dataset imobiliário do repositório:
if (file.exists("datasets/imobiliaria.csv")) {
  dados_imoveis <- read.csv("datasets/imobiliaria.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
  print(head(dados_imoveis, 3))
}

# 2. Leitura direta de arquivo compactado (.zip) sem descompactar no disco:
# dados_zip <- read.csv(unz("datasets/arquivo.zip", "conteudo.csv"), header = TRUE, sep = ";")

# 3. Exportando dados processados para CSV
write.csv(alunos, file = "alunos_processados.csv", row.names = FALSE)

# 4. Salvando e Carregando objetos nativos (.RData)
# O formato .RData preserva tipos, classes e atributos exatos do R de forma ultracompacta
save(alunos, aprovados_destaque, file = "dados_alunos.RData")

# 5. Gerenciamento do ambiente de execução
print("\nObjetos carregados na memória:")
print(ls())

# Removendo objetos temporários ou limpando a memória inteira:
rm(aprovados_destaque) # remove um objeto específico
# rm(list = ls())      # remove todas as variáveis do ambiente de trabalho (padrão em início de scripts)

## 6. Limpeza e Tratamento de Dados (Data Wrangling)
A qualidade da análise depende diretamente da higienização dos dados. Dados reais frequentemente contêm valores nulos (`NA`), tipos incorretos de variáveis e registros que necessitam de coerção ou substituição condicional.

In [ ]:
# Criando um dataset com problemas típicos para demonstração
amostra <- data.frame(
  id = 1:6,
  idade = c("23", "45", "desconhecido", "34", NA, "50"),
  salario = c(3500.50, 7200.00, 4100.00, NA, 5300.00, 12000.00),
  cidade = c("SP", "RJ", " sp ", "Curitiba", "RJ", "SP")
)
print("Dados originais com anomalias:")
print(amostra)

# 1. Identificação de dados faltantes (NA)
print("\nTotal de NAs no dataset:")
print(sum(is.na(amostra)))
print("\nNAs por coluna:")
print(colSums(is.na(amostra)))

# 2. Coerção segura de tipos: transformando idade em numérico
# Strings não numéricas ("desconhecido") são convertidas com segurança em NA
amostra$idade_num <- as.numeric(as.character(amostra$idade))

# 3. Imputação de valores faltantes (substituição do NA pela mediana ou média)
mediana_salario <- median(amostra$salario, na.rm = TRUE)
amostra$salario_imputado <- ifelse(is.na(amostra$salario), mediana_salario, amostra$salario)

# 4. Remoção de registros incompletos (quando a exclusão for justificada)
amostra_limpa <- na.omit(amostra[, c("id", "idade_num", "salario_imputado")])
print("\nDataset após coerção e tratamento de ausentes:")
print(amostra_limpa)

## 7. Manipulação de Strings e Expressões Regulares (Regex)
A maior parte do esforço de mineração de dados envolve higienizar textos livres (como nomes de cargos, cidades, faixas salariais ou datas formatadas de formas inconsistentes).

In [ ]:
# Vetor de textos brutos heterogêneos
locais <- c("São Paulo - SP", "Sao Paulo", "RIO DE JANEIRO", "Curitiba - PR", "  são paulo  ")

# 1. Remoção de espaços em branco nas extremidades
locais_trim <- trimws(locais)

# 2. Detecção de padrões (grepl retorna booleano, grep retorna índices/valores)
eh_sp <- grepl("s[aã]o paulo", locais_trim, ignore.case = TRUE)
print("Identificação de menções a São Paulo:")
print(eh_sp)

# 3. Substituição e padronização com sub (primeira ocorrência) e gsub (todas as ocorrências)
cargos <- c("Engenheiro Jr.", "Engenheiro Pleno", "Cientista de Dados Pleno", "Analista Jr.")
# Padronizando 'Jr.' para 'Junior'
cargos_padronizados <- gsub("Jr\\.", "Junior", cargos)
print("\nCargos com sufixo padronizado:")
print(cargos_padronizados)

# 4. Concatenação de textos com paste e paste0
codigos <- paste("COD", 101:104, sep = "_")
print("\nCódigos identificadores gerados:")
print(codigos)

# 5. Extração e contagem de caracteres
textos <- c("ID-9842", "ID-1123", "ID-0043")
tamanhos <- nchar(textos)
prefixo <- substr(textos, start = 1, stop = 2) # Extrai 'ID'
print(paste("Prefixo extraído:", prefixo[1], "| Tamanho:", tamanhos[1]))

## 8. Visualização de Dados (Base R & Jupyter)
Gráficos são fundamentais para entender a distribuição, identificar tendências e detectar *outliers*. No Jupyter Notebook, configuramos as dimensões da tela através do pacote `repr`.

In [ ]:
# Ajuste da resolução e proporção dos gráficos no Jupyter Notebook
if (requireNamespace("repr", quietly = TRUE)) {
  options(repr.plot.width = 11, repr.plot.height = 5)
}

# Criando dados sintéticos para visualização
set.seed(42)
area_m2 <- runif(60, min = 40, max = 250)
preco_mil <- 50 + 4.2 * area_m2 + rnorm(60, mean = 0, sd = 60)

# Divisão da tela em 2 gráficos lado a lado: par(mfrow = c(linhas, colunas))
par(mfrow = c(1, 2))

# 1. Gráfico de Dispersão (Scatterplot) com linha de tendência
plot(area_m2, preco_mil,
     main = "Preço vs Área Construída",
     xlab = "Área (m²)", ylab = "Preço (R$ mil)",
     pch = 19, col = "#2b5c8f")
# Adicionando linha de tendência estimada
abline(lm(preco_mil ~ area_m2), col = "#e63946", lwd = 2)
grid()

# 2. Boxplot (Diagrama de Caixas) para visualização de dispersão e outliers
boxplot(preco_mil,
        main = "Distribuição do Preço dos Imóveis",
        ylab = "Preço (R$ mil)",
        col = "#83c5be", border = "#006d77")

# Restaurando layout padrão para 1 gráfico por tela
par(mfrow = c(1, 1))

## 9. Estatística Descritiva, Correlação e Padronização
Antes de qualquer modelagem, calculamos medidas descritivas para entender escala, assimetria e associações lineares. Em seguida, aplicamos **padronização**, que é vital para comparar preditores e estabilizar algoritmos de machine learning.

In [ ]:
# Medidas de resumo univariado
cat("Média da área:", mean(area_m2), "\n")
cat("Mediana da área:", median(area_m2), "\n")
cat("Desvio padrão da área:", sd(area_m2), "\n")
cat("Amplitude Interquartil (IQR):", IQR(area_m2), "\n")
cat("Quantis [0%, 25%, 50%, 75%, 100%]:\n")
print(quantile(area_m2))

# Correlação Linear de Pearson entre duas variáveis contínuas
correlacao <- cor(area_m2, preco_mil)
cat("\nCoeficiente de Correlação de Pearson:", round(correlacao, 4), "\n")

# TÉCNICAS DE PADRONIZAÇÃO DE DADOS:
# 1. Z-Score / Z-Norm: média = 0 e desvio padrão = 1
#    Fórmula: z = (x - mean(x)) / sd(x)
area_znorm <- scale(area_m2) # função nativa do R

# 2. Min-Max Scaling: comprime os valores no intervalo fixo [0, 1]
#    Fórmula: x_norm = (x - min(x)) / (max(x) - min(x))
padroniz_minmax <- function(x) {
  return((x - min(x)) / (max(x) - min(x)))
}
area_minmax <- padroniz_minmax(area_m2)

cat("\nComparação das escalas:\n")
cat("Original [min, max]:", round(min(area_m2), 2), "a", round(max(area_m2), 2), "\n")
cat("Z-Norm [média, dp]:", round(mean(area_znorm), 2), "e", round(sd(area_znorm), 2), "\n")
cat("Min-Max [min, max]:", round(min(area_minmax), 2), "a", round(max(area_minmax), 2), "\n")

## 10. Modelagem Preditiva: Regressão Linear Simples e Múltipla
A regressão linear modela a relação entre uma variável contínua dependente ($Y$) e uma ou mais variáveis explicativas ($X$). Em R, o ajuste é realizado pela função `lm()` (*linear model*).

In [ ]:
# Criando um dataset com múltiplos atributos
df_imoveis <- data.frame(
  preco = preco_mil,
  area = area_m2,
  quartos = sample(1:4, 60, replace = TRUE),
  idade_imovel = runif(60, min = 0, max = 30)
)

# 1. Ajuste de Regressão Linear Simples: Y ~ X
modelo_simples <- lm(preco ~ area, data = df_imoveis)

# 2. Ajuste de Regressão Linear Múltipla: Y ~ X1 + X2 + ...
# Podemos incluir termos polinomiais com I(X^2)
modelo_multiplo <- lm(preco ~ area + quartos + idade_imovel + I(area^2), data = df_imoveis)

# Exibindo o resumo detalhado do modelo
print(summary(modelo_multiplo))

# 3. Predição e cálculo de métricas de erro
predicoes <- predict(modelo_multiplo, newdata = df_imoveis)
residuos <- df_imoveis$preco - predicoes

# Erro Absoluto Médio (MAE / EAM)
mae <- mean(abs(residuos))
# Erro Quadrático Médio (MSE / EQM)
mse <- mean(residuos^2)
# Raiz do Erro Quadrático Médio (RMSE / REQM)
rmse <- sqrt(mse)

cat("\n--- Métricas de Avaliação do Modelo ---\n")
cat("MAE (Erro Médio na mesma escala de Y):", round(mae, 2), "mil reais\n")
cat("MSE (Penaliza erros grandes):", round(mse, 2), "\n")
cat("RMSE (Desvio padrão dos resíduos):", round(rmse, 2), "mil reais\n")

## 11. Modelagem Preditiva: Regressão Logística e Classificação Binária
Quando a variável dependente é binária (0 ou 1, sucesso ou falha, potável ou não potável), a regressão linear comum é inadequada. Utilizamos a **Regressão Logística**, ajustada via `glm()` com a família `binomial`.

In [ ]:
# Criando uma variável binária de classificação: 'imovel_alto_padrao' (1 = Sim, 0 = Não)
df_imoveis$alto_padrao <- ifelse(df_imoveis$preco > median(df_imoveis$preco), 1, 0)

# 1. Ajuste do Modelo Logístico: logit(p) = beta0 + beta1*X1 + ...
modelo_logistico <- glm(alto_padrao ~ area + quartos, data = df_imoveis, family = binomial)
print(summary(modelo_logistico))

# 2. Obtenção das probabilidades preditas P(Y = 1 | X)
probabilidades <- predict(modelo_logistico, type = "response")

# 3. Aplicação do limiar de decisão (threshold padrão = 0.5)
limiar <- 0.5
classes_preditas <- ifelse(probabilidades >= limiar, 1, 0)

# 4. Matriz de Confusão
mat_confusao <- table(Observado = df_imoveis$alto_padrao, Predito = classes_preditas)
print("\nMatriz de Confusão:")
print(mat_confusao)

# 5. Cálculo manual das métricas essenciais de Classificação
vn <- mat_confusao[1, 1] # Verdadeiro Negativo
fp <- mat_confusao[1, 2] # Falso Positivo
fn <- mat_confusao[2, 1] # Falso Negativo
vp <- mat_confusao[2, 2] # Verdadeiro Positivo

acuracia <- (vp + vn) / sum(mat_confusao)
sensitividade <- vp / (vp + fn) # Recall / Taxa de Verdadeiro Positivo
especificidade <- vn / (vn + fp) # Taxa de Verdadeiro Negativo
precisao <- vp / (vp + fp)

cat("\n--- Indicadores de Qualidade do Classificador ---\n")
cat("Acurácia Geral:", round(acuracia * 100, 2), "%\n")
cat("Sensitividade (Recall):", round(sensitividade * 100, 2), "%\n")
cat("Especificidade:", round(especificidade * 100, 2), "%\n")
cat("Precisão:", round(precisao * 100, 2), "%\n")

## 12. Guia de Pacotes R Utilizados no Repositório
Abaixo está o inventário de pacotes externos utilizados nas análises deste repositório, com suas finalidades principais:

| Pacote | Finalidade Principal | Exemplo de Aplicação |
| :--- | :--- | :--- |
| `repr` | Controle do tamanho e aspecto de gráficos gerados no ambiente Jupyter. | `options(repr.plot.width = 11, repr.plot.height = 6)` |
| `stringr` | Manipulação consistente de cadeias de caracteres e regex do ecossistema Tidyverse. | `str_detect()`, `str_replace()`, `str_trim()` |
| `readr` | Ingestão veloz e automatizada de dados tabulares (CSV, TSV). | `read_csv()`, `read_delim()` |
| `corrplot` | Criação de gráficos visuais para matrizes de correlação com mapa de calor. | `corrplot(cor(dados), method = "circle")` |
| `car` | Diagnóstico econométrico e estatístico avançado de modelos de regressão. | `vif(modelo)` para diagnosticar multicolinearidade |
| `caret` | Framework integrado de Machine Learning para pré-processamento, split e validação. | `confusionMatrix()`, `createDataPartition()` |
| `ROCR` | Cálculo de curvas ROC, determinação de taxas TPR/FPR e cálculo numérico da AUC. | `prediction()`, `performance(pred, "tpr", "fpr")` |
| `Hmisc` | Pacote estatístico para análise exploratória profunda e correlações com p-valor. | `describe()`, `rcorr()` |
| `skimr` | Resumo visual rápido e completo das propriedades de todas as colunas de um dataset. | `skim(dados)` |