O mecanismo de atribuição em R é por meio do `<-` (`<`+`-`).  
Para notar um código, é comum colocar entre crase (\`) para indicar que não texto.

Por exemplo: "a variável `peso` não teve o mesmo desempenho que `altura`.

In [3]:
a <- 8
10 -> b

In [4]:
a
b

[1] 8

[1] 10

In [5]:
(h <- 21)  # atribuição preferencial

[1] 21

In [6]:
h <- 21
h

[1] 21

A fórmula da média é $ \bar{x} = \frac{\sum x_i}{n}$

In [7]:
a

[1] 8

O texto pode estar em _itálico_, **negrito** ou ***negrito e itálico***.

# Introdução

## Estudo de caso

### parte 1

A mensagem original:
> Vai pra casa.
>> onde você está?}

O comando utilizado na consulta foi:

```SQL
SELECT * FROM Cliente
 INNER JOIN Compra ON (Cliente.cod = Compra.cliente);
```

In [23]:
a <- "CDAD"

In [24]:
a

[1] "CDAD"

In [25]:
is.integer(b)

[1] FALSE

In [26]:
b

[1] 20

In [27]:
print(b)

[1] 20

In [28]:
print(1:200)

  [1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
[109] 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
[127] 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
[145] 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
[163] 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
[181] 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
[199] 199 200

In [29]:
h <- 25; g <- 40
h
g

[1] 25

[1] 40

In [30]:
cliente.nome <- "Lucas"

In [31]:
produto. <- "Pão"

In [32]:
custo_inicial_base <- 123.12

In [33]:
paciente$sexo <- "M"

ERROR: Error: object 'paciente' not found

In [34]:
soma <- function(x,y=10) {x + y}

In [35]:
soma(4)

[1] 14

In [36]:
soma(2,7)

[1] 9

In [37]:
class(soma)

[1] "function"

In [38]:
class(b)

[1] "numeric"

In [39]:
b <- 20

In [40]:
b

[1] 20

In [41]:
a <- b == 30

In [42]:
a

[1] FALSE

In [43]:
a + a

[1] 0

In [45]:
!a + 3
3 + !a

[1] FALSE

[1] 4

definição de vetor com a função `c()`

remover variável da memória
`rm(lista)`

In [9]:
rm(a,b)

Warning message in rm(a, b):
“object 'a' not found”

In [51]:
v <- c(1,4,6,2,7,0)
v

[1] 1 4 6 2 7 0

In [47]:
v[1]

[1] 1

In [48]:
v[5]

[1] 7

In [54]:
v
v[c(5,1,3,6)] # lista de índices

[1] 1 4 6 2 7 0

[1] 7 1 6 0

In [55]:
v[-3]
v

[1] 1 4 2 7 0

[1] 1 4 6 2 7 0

In [58]:
v[-c(1,3,6)]

[1] 4 2 7

In [59]:
v1 <- c(-1,1,0)
v2 <- c(4,5,6)

In [60]:
v1+v2

[1] 3 6 6

In [61]:
v1-v2

[1] -5 -4 -6

In [62]:
c(v1,v2)

[1] -1  1  0  4  5  6

In [63]:
v3 <- c(11,12,13,14)

In [65]:
v3
v1

[1] 11 12 13 14

[1] -1  1  0

In [64]:
v3-v1

Warning message in v3 - v1:
“longer object length is not a multiple of shorter object length”

[1] 12 11 13 15

In [66]:
v4 <- c(5,6)

In [67]:
v3
v4
v3-v4

[1] 11 12 13 14

[1] 5 6

[1] 6 6 8 8

In [68]:
v5 <- c(1:10)
v5

 [1]  1  2  3  4  5  6  7  8  9 10

In [70]:
v6 <- c(-1,1,10:0)
v6

 [1] -1  1 10  9  8  7  6  5  4  3  2  1  0

In [73]:
v5
logico <- v5 %% 2 == 0
logico

 [1]  1  2  3  4  5  6  7  8  9 10

 [1] FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE

In [74]:
v5[logico]

[1]  2  4  6  8 10

In [75]:
v5[!logico]

[1] 1 3 5 7 9

In [76]:
c(v5[logico], v5[!logico])

 [1]  2  4  6  8 10  1  3  5  7  9

### Exercícios

1 - Crie um vetor `v` de 10 posições numéricas

In [78]:
v <- c(4,3,2, 1,12,11, 10,9,8, 7)
v

 [1]  4  3  2  1 12 11 10  9  8  7

2 - salve as posições 2,3,5 e 9 de `v` em um novo vetor `s`.

In [79]:
s <- v[c(2,3,5,9)]
s

[1]  3  2 12  8

3 - Obtenha um vetor `t` com apenas os valores maiores que 10 de `v`.

In [80]:
v
maior10 <- v > 10
maior10
t <- v[maior10]
t

 [1]  4  3  2  1 12 11 10  9  8  7

 [1] FALSE FALSE FALSE FALSE  TRUE  TRUE FALSE FALSE FALSE FALSE

[1] 12 11

In [87]:
t <- v[v>10]
t

[1] 12 11

4 - Obtenha um vetor `u` sem as posições 1,2,3,8,9 e 10 de `v`.

In [81]:
u <- v[-c(1,2,3,8,9,10)]
u

[1]  1 12 11 10

In [83]:
v
v[c(4,1:3,10:5)]

 [1]  4  3  2  1 12 11 10  9  8  7

 [1]  1  4  3  2  7  8  9 10 11 12

In [84]:
x <- c(1,2,3)
x <- c(x,x,x,x)
x

 [1] 1 2 3 1 2 3 1 2 3 1 2 3

In [86]:
rep(c(1,2,3),4)

 [1] 1 2 3 1 2 3 1 2 3 1 2 3

In [44]:
v + 1

[1] 2 5 7 3 8 1

In [88]:
v <- c(1:10)
v
v[9]

 [1]  1  2  3  4  5  6  7  8  9 10

[1] 9

In [89]:
v[5] <- -8
v

 [1]  1  2  3  4 -8  6  7  8  9 10

In [90]:
v[20]

[1] NA

In [94]:
v[20] <- 20
v

 [1]  1  2  3  4 -8  6  7  8  9 10 NA NA NA NA NA NA NA NA NA 20

In [95]:
v <- v[1:10]
v

 [1]  1  2  3  4 -8  6  7  8  9 10

In [96]:
v1 <- c(1,2,3)
v2 <- c(FALSE,TRUE,FALSE)
v3 <- c('A','B','C')

In [97]:
v1 + v2

[1] 1 3 3

In [98]:
v2 + v1

[1] 1 3 3

In [99]:
v1 + v3

ERROR: Error in v1 + v3: non-numeric argument to binary operator

In [100]:
c(v1,v2)

[1] 1 2 3 0 1 0

In [101]:
c(v2,v1)

[1] 0 1 0 1 2 3

In [102]:
c(v1,v3)

[1] "1" "2" "3" "A" "B" "C"

In [103]:
c(v1,v2,v3)
c(v3,v2,v1)

[1] "1"     "2"     "3"     "FALSE" "TRUE"  "FALSE" "A"     "B"     "C"

[1] "A"     "B"     "C"     "FALSE" "TRUE"  "FALSE" "1"     "2"     "3"

In [104]:
c(c(v1,v2),v3)

[1] "1" "2" "3" "0" "1" "0" "A" "B" "C"

In [105]:
v1

[1] 1 2 3

In [106]:
sum(v1)

[1] 6

In [107]:
v1/3 + sqrt(v1)

[1] 1.333333 2.080880 2.732051

In [108]:
LETTERS

 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [109]:
letters

 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

In [111]:
number

ERROR: Error: object 'number' not found

Matriz

In [112]:
v <- 1:20
v

 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

In [117]:
matrix(v,ncol=7, byrow=TRUE)

Warning message in matrix(v, ncol = 7, byrow = TRUE):
“data length [20] is not a sub-multiple or multiple of the number of rows [3]”

     [,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,]  1    2    3    4    5    6    7
[2,]  8    9   10   11   12   13   14
[3,] 15   16   17   18   19   20    1

In [118]:
nome <- c("Abel","Bianca","Caio","Dênis","Ema", "Fabio", "Gus", "Helena")
nota <- c(   6.5,     9.3,   2.2,    6.9,  7.0,     8.4,   7.1,      7.9)
freq <- c(  0.68,    0.81,  0.57,   0.71, 0.83,    0.90,  0.85,     0.78)
sexo <- c(   'M',     'F',   'M',    'M',  'F',     'M',   'X',      'F')

In [119]:
nome

[1] "Abel"   "Bianca" "Caio"   "Dênis"  "Ema"    "Fabio"  "Gus"    "Helena"

In [120]:
sexo

[1] "M" "F" "M" "M" "F" "M" "X" "F"

In [121]:
classe <- data.frame(nome,nota,freq,sexo)
classe

  nome   nota freq sexo
1 Abel   6.5  0.68 M
2 Bianca 9.3  0.81 F
3 Caio   2.2  0.57 M
4 Dênis  6.9  0.71 M
5 Ema    7.0  0.83 F
6 Fabio  8.4  0.90 M
7 Gus    7.1  0.85 X
8 Helena 7.9  0.78 F

In [123]:
classe[1,4]

[1] "M"

In [124]:
classe[2,3]

[1] 0.81

In [125]:
classe[2:5,3]

[1] 0.81 0.57 0.71 0.83

In [126]:
classe[c(2,5,7),c(1,3,4)]

  nome   freq sexo
2 Bianca 0.81 F
5 Ema    0.83 F
7 Gus    0.85 X

In [128]:
classe[-3,]

  nome   nota freq sexo
1 Abel   6.5  0.68 M
2 Bianca 9.3  0.81 F
4 Dênis  6.9  0.71 M
5 Ema    7.0  0.83 F
6 Fabio  8.4  0.90 M
7 Gus    7.1  0.85 X
8 Helena 7.9  0.78 F

In [129]:
class(classe)

[1] "data.frame"

In [130]:
classe[classe$nota>7 & classe$freq>0.8,1]

[1] "Bianca" "Fabio"  "Gus"

In [131]:
mean(classe[classe$nota>7 & classe$freq>0.8,2])

[1] 8.266667