# Introdução ao R

No R, tudo é um objeto. Objetos podem ser de diferentes tipos, como vetores, matrizes, listas, data frames, funções, etc. Atribuímos valores a objetos usando o operador `<-`. Por exemplo:

In [1]:
a <- 8
10 -> b
a
b

[1] 8

[1] 10

> Note que é possível usar tanto `<-` quanto `->` para atribuição, mas a convenção é sempre usar `<-`.

## Variáveis

O R possui uma relação muito similar com o python quando se trata de variáveis. Por exemplo, você pode criar uma variável `a` e atribuir um valor a ela, e depois criar outra variável `b` e atribuir outro valor. Você pode acessar o valor de uma variável simplesmente digitando seu nome.

R não é fortemente tipado, o que significa que você pode mudar o tipo de um objeto ao longo do tempo. Por exemplo:

In [2]:
a <- 8
a
a <- "Oito"
a

[1] 8

[1] "Oito"

Porém, é possível utilizar funções como `is.numeric()` para verificar o tipo de um objeto.

Além disso, variáveis do tipo bool são um caso especial, pois podem assumir apenas dois valores: `TRUE` ou `FALSE`, porém são tratadas como 1 ou 0 no R. Fazendo com que coisas assim possam acontecer:

In [3]:
booleano <- TRUE
x <- 1

# Comparando booleano com x
booleano == x  # TRUE, pois TRUE é tratado como 1

[1] TRUE

Por outro lado, se você fizer uma operação matemática com um booleano, ele será convertido para 1 ou 0.  Por exemplo:

In [4]:
booleano + x  # 1
x + booleano  # 2

booleano * x  # 1

[1] 2

[1] 2

[1] 1

Mas, se utilizarmos um operador de negação, o resultado das contas tendem a possuir o tipo da primeira variável. Por exemplo:

In [5]:
!booleano + x # FALSE, pois a primeira variável é booleana
x + !booleano # 1, pois a primeira variável é numerica

[1] FALSE

[1] 1

### Nomes de variáveis

É válido ressaltar que em R o `.` (ponto) é um caractere válido para nomes de objetos, mas não é recomendado começar nomes de objetos com números ou usar caracteres especiais. Para acessar atributos de um objeto, você pode usar o operador `$`. Por exemplo:

In [6]:
cliente.nome <- "Lucas"
cliente.nome

[1] "Lucas"

In [7]:
# Criando um objeto cliente com atributos
cliente <- list(nome = "Lucas", idade = 30, cidade = "São Paulo")

# Acessando atributos do objeto cliente
cliente$nome
cliente$idade
cliente$cidade

[1] "Lucas"

[1] 30

[1] "São Paulo"

R possui algumas peculiaridades em relação a nomes de variáveis. Por exemplo, nomes de variáveis podem conter letras, números e o caractere `_`, mas não podem começar com um número. Além disso, R é case-sensitive, ou seja, `variavel` e `Variavel` são consideradas variáveis diferentes.

## Funções

Em R, funções são objetos de primeira classe, o que significa que você pode atribuí-las a variáveis, passá-las como argumentos para outras funções e retorná-las de funções. Por exemplo:

In [8]:
soma <- function(x, y) {
  return(x + y)
}
soma(2, 3)

[1] 5

Além disso, R possui muitas funções embutidas que você pode usar diretamente. Exemplo das principais funções embutidas:

In [9]:
# mean() -> Calcula a média de um vetor
mean(c(1, 2, 3, 4, 5))

[1] 3

In [10]:
# rm(lista) -> remove uma variável da memória
rm(a, b)

In [11]:
# rep(c(), x) -> concatena um vetor (ou não) com ele mesmo x vezes
rep(c(1, 2, 3), 3)

[1] 1 2 3 1 2 3 1 2 3

In [12]:
# sum(c()) -> soma uma lista inteira
sum(c(1, 2, 3, 4, 5))

[1] 15

In [13]:
# sqrt(x) -> faz raíz quadrada de um número
# pode ser usado um vetor de parâmetro para aplicar a cada item do vetor
sqrt(4)
sqrt(c(1, 4, 9, 16))

[1] 2

[1] 1 2 3 4

In [14]:
# ls() -> Lista as variáveis carregadas na memória no momento
ls()

[1] "booleano"     "cliente"      "cliente.nome" "soma"         "x"

In [15]:
# save(var, file = "nome_do_arquivo.RData") -> Salva um objeto em um arquivo .RData
save(cliente, file = "cliente.RData")

In [16]:
# load("nome_do_arquivo.RData") -> Carrega um objeto salvo em um arquivo .RData
load("cliente.RData")

## Vetores

Em R, tudo é vetor, porém, podemos criar nossos próprios vetores utilizando a função `c()`.

In [17]:
v <- c(1,9,0,3,4,8,6,0,9,8)
v

 [1] 1 9 0 3 4 8 6 0 9 8

O acesso ao vetor é feito como em outras linguagens através do `vetor[index]`, porém é importante ressaltar, que R não possui indexação como em outras linguagens, o index inicial é o `1` e não o `0`.

In [18]:
v[1]
v[2]
v[3]

[1] 1

[1] 9

[1] 0

Também é possível selecionar uma lista de indíces para serem exibidos. Neste caso, o resultado será um novo vetor.

In [19]:
v[c(1, 2, 3)]

[1] 1 9 0

Além disso, é possível selecionar valores negativos no índice, o que irá fazer com que o vetor apresente todos os índices, menos o selecionado. Além de possuir uma variação com um vetor de indíces.

In [20]:
v[-1]
v[-c(1,2,3)]

[1] 9 0 3 4 8 6 0 9 8

[1] 3 4 8 6 0 9 8

Além disso, é possível fazer operações com vetores, por exemplo:

In [21]:
v1 <- c(1, 2, 3, 4, 5)
v2 <- c(4, 5, 6, 7, 8)

# Opera a cada valor do vetor
v1 + v2
v1 - v2
v1 + 1

# Concatena os vetores
c(v1, v2)

[1]  5  7  9 11 13

[1] -3 -3 -3 -3 -3

[1] 2 3 4 5 6

 [1] 1 2 3 4 5 4 5 6 7 8

Para vetores de tamanhos diferentes, há uma pequena diferença. Quando o vetor menor chega no último valor, ele volta do início operando novamente, gerando sempre, como resultado, um vetor do tamanho do maior. Caso o objeto maior seja múltiplo do menor, operará normalmente, caso contrário, irá operar, porém gerar um warning. Por exemplo:

In [22]:
v3 <- c(20:29)
v4 <- c(1:4)

# Soma de vetores de mesmo tamanho
v1 + v2

# Soma de vetores de tamanho múltiplo
v1 + v3

# Soma de vetores de tamanhos diferentes
v1 + v4

[1]  5  7  9 11 13

 [1] 21 23 25 27 29 26 28 30 32 34

Warning message in v1 + v4:
“comprimento do objeto maior não é múltiplo do comprimento do objeto menor”

[1] 2 4 6 8 6

Existem formas simples de fazer uma filtragem em vetores, principalmente numéricos. Caso haja um vetor booleano, o resultado será o vetor com apenas com os valores `TRUE`.

In [23]:
v5 <- c(1:10)
v5

# Criando o filtro
filtro <- v5 %% 2 == 0
filtro

v5[filtro]

 [1]  1  2  3  4  5  6  7  8  9 10

 [1] FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE

[1]  2  4  6  8 10

É possível adicionar valores em posições específicas do vetor, por exemplo `v[5]`. Porém, caso a posição que tente adicionar seja uma posição maior que a última posição, o vetor é preenchido com `<NA>` (o `null` de outras linguagens) até a posição desejada.

In [24]:
v
v[15] <- 10
v

 [1] 1 9 0 3 4 8 6 0 9 8

 [1]  1  9  0  3  4  8  6  0  9  8 NA NA NA NA 10

Quando se há tipos de diferentes de dados em vetores, algumas coisas podem acontecer.

Primeiro, operações podem ser feitas entre vetores de tipos numéricos e tipos derivados de numéricos, como o booleano.

Segundo, quando há a concatenação de vetores, o tipo mais primitivo tende a ser usado para o resultado final, seguindo a ordem de `character` > `numeric` > `boolean`. Exemplos:

In [25]:
v1 <- c(1,2,3)
v2 <- c(FALSE,TRUE,FALSE)
v3 <- c('A','B','C')

# numeric + boolean
v1 + v2

# numeric + character = error
# v1 + v3

# concat: numeric + boolean
c(v1, v2)

# concat: numeric + character
c(v1, v3)

# concat: boolean + character
c(v2, v3)

[1] 1 3 3

[1] 1 2 3 0 1 0

[1] "1" "2" "3" "A" "B" "C"

[1] "FALSE" "TRUE"  "FALSE" "A"     "B"     "C"

### Matriz

Matrizes nada mais são do que vetores com mais de uma dimensão. Em R, é possível fazer isso de forma simples utilizando a função `matrix()`. Para utilizá-la, é preciso passar alguns parâmetros: um vetor e `ncol` = quantidade de colunas que terá ou `nrow` = quantidade de linhas que terá. Normalmente, caso você utilize `ncol`, a tabela será construída por colunas, mas é possível fazer que ela seja construída por linhas usando o parâmetro `byrow=TRUE`. O caso contrário (`nrow` e `byrow=FALSE`) também pode ser feito.

Além disso, o número de colunas (ou de linhas) deve ser um divisor do tamanho do vetor, caso contrário, ele gerará um warning avisando, mas fará o mesmo que fez com as operações entre vetores, começará a repetir o vetor para preencher as lacunas.

In [26]:
v <- 1:12

vcol <- matrix(v, ncol = 3)
vrow <- matrix(v, nrow = 3)

vcol_byrow <- matrix(v, ncol = 3, byrow = TRUE)
vrow_bycol <- matrix(v, nrow = 3, byrow = FALSE)

v_wrongCol <- matrix(v, ncol = 5, byrow = TRUE)

vcol
vrow
vcol_byrow
vrow_bycol
v_wrongCol

Warning message in matrix(v, ncol = 5, byrow = TRUE):
“data length [12] is not a sub-multiple or multiple of the number of columns [5]”

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

     [,1] [,2] [,3] [,4]
[1,] 1    4    7    10
[2,] 2    5    8    11
[3,] 3    6    9    12

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12

     [,1] [,2] [,3] [,4]
[1,] 1    4    7    10
[2,] 2    5    8    11
[3,] 3    6    9    12

     [,1] [,2] [,3] [,4] [,5]
[1,]  1    2   3    4     5
[2,]  6    7   8    9    10
[3,] 11   12   1    2     3

## DataFrame

DataFrames são conjuntos de dados, onde teremos uma tabela com atributos e seus valores. Para montá-los são necessários vetores de tamanhos iguais (se forem diferentes serão preenchidos como `<NA>`). Onde o próprio nome da variável será usado como cabeçalho. Exemplo:

In [27]:
nome <- c("Abel","Bianca","Caio","Dênis","Ema", "Fabio", "Gus", "Helena")
nota <- c(   6.5,     9.3,   2.2,    6.9,  7.0,     8.4,   7.1,      7.9)
freq <- c(  0.68,    0.81,  0.57,   0.71, 0.83,    0.90,  0.85,     0.78)
sexo <- c(   'M',     'F',   'M',    'M',  'F',     'M',   'X',      'F')

alunos <- data.frame(nome,nota,freq,sexo)
alunos

  nome   nota freq sexo
1 Abel   6.5  0.68 M
2 Bianca 9.3  0.81 F
3 Caio   2.2  0.57 M
4 Dênis  6.9  0.71 M
5 Ema    7.0  0.83 F
6 Fabio  8.4  0.90 M
7 Gus    7.1  0.85 X
8 Helena 7.9  0.78 F

Assim como as matrizes, nos DataFrames podemos utilizar coordenadas para pegar dados específicos. Por exemplo:

In [28]:
# Pegando valores específicos:
alunos[2,3]

# Pegando intervalos
alunos[2:5, 1]

# Pegando listas
alunos[c(2, 5, 7), c(1, 2, 3)]

[1] 0.81

[1] "Bianca" "Caio"   "Dênis"  "Ema"

  nome   nota freq
2 Bianca 9.3  0.81
5 Ema    7.0  0.83
7 Gus    7.1  0.85

Para acessar os dados, podemos utilizar também os `$`, pegando assim a coluna inteira. Permitindo que possamos fazer diversas coisas, inclusive operações. Por exemplo:

In [29]:
# Nome dos alunos com nota maior que 80%:
alunos[alunos$freq > 0.8, 1]

# Média dos alunos com frequência maior que 75%:
mean(alunos[alunos$freq > 0.75, 2])

[1] "Bianca" "Ema"    "Fabio"  "Gus"

[1] 7.94