O mecanismo de atribuição em R é por meio do `<-` (`<`+`-`).  
Para notar um código, é comum colocar entre crase (\`) para indicar que não texto.

Por exemplo: "a variável `peso` não teve o mesmo desempenho que `altura`.

In [164]:
a <- 8
10 -> b

In [165]:
a
b

[1] 8

[1] 10

In [166]:
(h <- 21)  # atribuição preferencial

[1] 21

In [167]:
h <- 21
h

[1] 21

A fórmula da média é $ \bar{x} = \frac{\sum x_i}{n}$

In [168]:
a

[1] 8

O texto pode estar em _itálico_, **negrito** ou ***negrito e itálico***.

# Introdução

## Estudo de caso

### parte 1

A mensagem original:
> Vai pra casa.
>> onde você está?}

O comando utilizado na consulta foi:

```SQL
SELECT * FROM Cliente
 INNER JOIN Compra ON (Cliente.cod = Compra.cliente);
```

In [169]:
a <- "CDAD"

In [170]:
a

[1] "CDAD"

In [171]:
is.integer(b)

[1] FALSE

In [172]:
b

[1] 10

In [173]:
print(b)

[1] 10

In [174]:
print(1:200)

  [1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
[109] 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
[127] 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
[145] 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
[163] 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
[181] 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
[199] 199 200

In [175]:
h <- 25; g <- 40
h
g

[1] 25

[1] 40

In [1]:
cliente.nome <- "Lucas"

In [177]:
produto. <- "Pão"

In [178]:
custo_inicial_base <- 123.12

In [179]:
# paciente$sexo <- "M"

In [6]:
soma <- function(x,y=10) {x + y}

In [181]:
soma(4)

[1] 14

In [7]:
soma(2,7)

[1] 9

In [8]:
class(soma)

[1] "function"

In [184]:
class(b)

[1] "numeric"

In [185]:
b <- 20

In [186]:
b

[1] 20

In [187]:
a <- b == 30

In [188]:
a

[1] FALSE

In [189]:
a + a

[1] 0

In [190]:
!a + 3
3 + !a

[1] FALSE

[1] 4

definição de vetor com a função `c()`

remover variável da memória
`rm(lista)`

In [191]:
rm(a,b)

In [10]:
v <- c(1,4,6,2,7,0)
v

[1] 1 4 6 2 7 0

In [193]:
v[1]

[1] 1

In [194]:
v[5]

[1] 7

In [195]:
v
v[c(5,1,3,6)] # lista de índices

[1] 1 4 6 2 7 0

[1] 7 1 6 0

In [12]:
v[-3]
v

[1] 1 4 2 7 0

[1] 1 4 6 2 7 0

In [197]:
v[-c(1,3,6)]

[1] 4 2 7

In [198]:
v1 <- c(-1,1,0)
v2 <- c(4,5,6)

In [199]:
v1+v2

[1] 3 6 6

In [200]:
v1-v2

[1] -5 -4 -6

In [201]:
c(v1,v2)

[1] -1  1  0  4  5  6

In [202]:
v3 <- c(11,12,13,14)

In [203]:
v3
v1

[1] 11 12 13 14

[1] -1  1  0

In [204]:
v3-v1

Warning message in v3 - v1:
“comprimento do objeto maior não é múltiplo do comprimento do objeto menor”

[1] 12 11 13 15

In [205]:
v4 <- c(5,6)

In [206]:
v3
v4
v3-v4

[1] 11 12 13 14

[1] 5 6

[1] 6 6 8 8

In [207]:
v5 <- c(1:10)
v5

 [1]  1  2  3  4  5  6  7  8  9 10

In [208]:
v6 <- c(-1,1,10:0)
v6

 [1] -1  1 10  9  8  7  6  5  4  3  2  1  0

In [209]:
v5
logico <- v5 %% 2 == 0
logico

 [1]  1  2  3  4  5  6  7  8  9 10

 [1] FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE

In [210]:
v5[logico]

[1]  2  4  6  8 10

In [211]:
v5[!logico]

[1] 1 3 5 7 9

In [212]:
c(v5[logico], v5[!logico])

 [1]  2  4  6  8 10  1  3  5  7  9

### Exercícios

1 - Crie um vetor `v` de 10 posições numéricas

In [213]:
v <- c(4,3,2, 1,12,11, 10,9,8, 7)
v

 [1]  4  3  2  1 12 11 10  9  8  7

2 - salve as posições 2,3,5 e 9 de `v` em um novo vetor `s`.

In [214]:
s <- v[c(2,3,5,9)]
s

[1]  3  2 12  8

3 - Obtenha um vetor `t` com apenas os valores maiores que 10 de `v`.

In [215]:
v
maior10 <- v > 10
maior10
t <- v[maior10]
t

 [1]  4  3  2  1 12 11 10  9  8  7

 [1] FALSE FALSE FALSE FALSE  TRUE  TRUE FALSE FALSE FALSE FALSE

[1] 12 11

In [216]:
t <- v[v>10]
t

[1] 12 11

4 - Obtenha um vetor `u` sem as posições 1,2,3,8,9 e 10 de `v`.

In [217]:
u <- v[-c(1,2,3,8,9,10)]
u

[1]  1 12 11 10

In [218]:
v
v[c(4,1:3,10:5)]

 [1]  4  3  2  1 12 11 10  9  8  7

 [1]  1  4  3  2  7  8  9 10 11 12

In [219]:
x <- c(1,2,3)
x <- c(x,x,x,x)
x

 [1] 1 2 3 1 2 3 1 2 3 1 2 3

In [220]:
rep(c(1,2,3),4)

 [1] 1 2 3 1 2 3 1 2 3 1 2 3

In [221]:
v + 1

 [1]  5  4  3  2 13 12 11 10  9  8

In [222]:
v <- c(1:10)
v
v[9]

 [1]  1  2  3  4  5  6  7  8  9 10

[1] 9

In [223]:
v[5] <- -8
v

 [1]  1  2  3  4 -8  6  7  8  9 10

In [224]:
v[20]

[1] NA

In [225]:
v[20] <- 20
v

 [1]  1  2  3  4 -8  6  7  8  9 10 NA NA NA NA NA NA NA NA NA 20

In [226]:
v <- v[1:10]
v

 [1]  1  2  3  4 -8  6  7  8  9 10

In [13]:
v1 <- c(1,2,3)
v2 <- c(FALSE,TRUE,FALSE)
v3 <- c('A','B','C')

In [228]:
v1 + v2

[1] 1 3 3

In [229]:
v2 + v1

[1] 1 3 3

In [15]:
v1 + v3

ERROR: Error in v1 + v3: argumento não-numérico para operador binário

In [17]:
c(v1,v2)

[1] 1 2 3 0 1 0

[1] 1 2 3 0 1 0

In [18]:
c(v2,v1)

[1] 0 1 0 1 2 3

In [233]:
c(v1,v3)

[1] "1" "2" "3" "A" "B" "C"

In [234]:
c(v1,v2,v3)
c(v3,v2,v1)

[1] "1"     "2"     "3"     "FALSE" "TRUE"  "FALSE" "A"     "B"     "C"

[1] "A"     "B"     "C"     "FALSE" "TRUE"  "FALSE" "1"     "2"     "3"

In [235]:
c(c(v1,v2),v3)

[1] "1" "2" "3" "0" "1" "0" "A" "B" "C"

In [236]:
v1

[1] 1 2 3

In [237]:
sum(v1)

[1] 6

In [238]:
v1/3 + sqrt(v1)

[1] 1.333333 2.080880 2.732051

In [239]:
LETTERS

 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [240]:
letters

 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

Matriz

In [19]:
v <- 1:20
v

 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

In [20]:
matrix(v,ncol=5, byrow=TRUE)

     [,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5
[2,]  6    7    8    9   10
[3,] 11   12   13   14   15
[4,] 16   17   18   19   20

In [243]:
nome <- c("Abel","Bianca","Caio","Dênis","Ema", "Fabio", "Gus", "Helena")
nota <- c(   6.5,     9.3,   2.2,    6.9,  7.0,     8.4,   7.1,      7.9)
freq <- c(  0.68,    0.81,  0.57,   0.71, 0.83,    0.90,  0.85,     0.78)
sexo <- c(   'M',     'F',   'M',    'M',  'F',     'M',   'X',      'F')

In [244]:
nome

[1] "Abel"   "Bianca" "Caio"   "Dênis"  "Ema"    "Fabio"  "Gus"    "Helena"

In [245]:
sexo

[1] "M" "F" "M" "M" "F" "M" "X" "F"

In [246]:
classe <- data.frame(nome,nota,freq,sexo)
classe

  nome   nota freq sexo
1 Abel   6.5  0.68 M
2 Bianca 9.3  0.81 F
3 Caio   2.2  0.57 M
4 Dênis  6.9  0.71 M
5 Ema    7.0  0.83 F
6 Fabio  8.4  0.90 M
7 Gus    7.1  0.85 X
8 Helena 7.9  0.78 F

In [247]:
classe[1,4]

[1] "M"

In [248]:
classe[2,3]

[1] 0.81

In [249]:
classe[2:5,3]

[1] 0.81 0.57 0.71 0.83

In [250]:
classe[c(2,5,7),c(1,3,4)]

  nome   freq sexo
2 Bianca 0.81 F
5 Ema    0.83 F
7 Gus    0.85 X

In [251]:
classe[-3,]

  nome   nota freq sexo
1 Abel   6.5  0.68 M
2 Bianca 9.3  0.81 F
4 Dênis  6.9  0.71 M
5 Ema    7.0  0.83 F
6 Fabio  8.4  0.90 M
7 Gus    7.1  0.85 X
8 Helena 7.9  0.78 F

In [252]:
class(classe)

[1] "data.frame"

In [253]:
classe[classe$nota>7 & classe$freq>0.8,1]

[1] "Bianca" "Fabio"  "Gus"

In [254]:
mean(classe[classe$nota>7 & classe$freq>0.8,2])

[1] 8.266667

Listar os nomes dos alunos com frequência maior que 80%

In [257]:
classe[classe$freq>0.8, "nome"]

[1] "Bianca" "Ema"    "Fabio"  "Gus"

Listar alunos aprovados (nota >= 6.0 e freq >= 75%)

In [260]:
aprovados <- classe$nota >= 6.0 & classe$freq >= 0.75
classe[aprovados,]

  nome   nota freq sexo
2 Bianca 9.3  0.81 F
5 Ema    7.0  0.83 F
6 Fabio  8.4  0.90 M
7 Gus    7.1  0.85 X
8 Helena 7.9  0.78 F

Listar nota e frequência dos alunos reprovados por nota mas aprovados por frequência

In [264]:
reprovados_freq <- classe$nota>=6.0 & classe$freq<0.75
classe[reprovados_freq, c("nota", "freq")]

  nota freq
1 6.5  0.68
4 6.9  0.71

ls(), save(var, file=".RData"), load(".RData")